name: Assemble and Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assemble
        run: |
          cat bchunk_aa bchunk_ab bchunk_ac bchunk_ad > index.html
      - name: Commit and Push
        run: |
          git config --global user.name "Zapia Max"
          git config --global user.email "zapia-max@users.noreply.github.com"
          git add index.html
          git rm bchunk_aa bchunk_ab bchunk_ac bchunk_ad
          git commit -m 'FIX: Contadores de activos y botón de refresco de suscripción'
          git push
