name: Fix Index
on: push
jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Join
        run: |
          cat p_aa p_ab p_ac p_ad p_ae p_af p_ag | base64 -d > index.html
          git config user.name "Zapia"
          git config user.email "zapia@example.com"
          git add index.html
          git rm p_aa p_ab p_ac p_ad p_ae p_af p_ag
          git commit -m "Restore index.html"
          git push
