name: Manual Sync
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sed UI
        run: |
          sed -i 's/id="perfilPlan">DEMO/id="perfilPlan">ADMIN PRO/g' index.html
          git config --local user.email "florenciaamor36@gmail.com"
          git config --local user.name "Zapia AI"
          git commit -am "Manual UI Sync" || exit 0
          git push
