name: PATCH
on: workflow_dispatch
jobs:
  p:
    runs-on: ubuntu-latest
    permissions: {contents: write}
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed -i "/Token de Acceso/,/<hr>/d" index.html
          sed -i "/btnIrToken/d" index.html
          git config user.name Bot; git config user.email bot@bot.com; git add .; git commit -m SaaS; git push