name: RESCUEV2
on: workflow_dispatch
permissions:
  contents: write jobs:
  rescue:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: |
          sed -i '/admin.css/d' index.html
          sed -i '/admin.js/d' index.html
          git config user.name "Rescue Bot"
          git config user.email "rescue@zapia.com"
          git commit -am "FORCE RESTORE UI" || exit 0
          git push