name: SaaS Simple
on: workflow_dispatch
jobs:
  patch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - uses: actions/checkout@v4
      - run: |
          sed -i 's|</head>|  <link rel="stylesheet" href="admin.css2>\n</head>|' index.html
          sed -i 's|</body>|<script src="admin.js"></script>\n/</body>|' index.html
          git config user.name "Z"
          git config user.email "z@z.com"
          git commit -am "SaaS"
          git push