name: SUP
on: workflow_dispatch
jobs:
  s:
    runs-on: ubuntu-latest
    permissions: {contents: write}
    steps:
      - uses: actions/checkout@v4
      - run: |
          sed -i "s/<button class="nav-btn" data-nav="ayuda">/<button class="nav-btn" id="btnSoporte">/g" index.html
          sed -i "s/<span>Ayuda<\/span>/<span>Soporte<\/span>/g" index.html
          sed -i "s/fas fa-question-circle/fab fa-whatsapp/g" index.html
          git config user.name Bot; git config user.email bot@bot.com; git add .; git commit -m Support; git push